package com.tekorero.attendance.model;

public enum RegularizationReason {
	
	BUSINESSMEETING,
	BUSINESSTRAVEL,
	CLIENTVISIT,
	CAPTIVELOCATION,
	ELECTION,
	EXTERNALRECRUITMENTDRIVE,
	EXTERNALTRAININGPROGRAM,
	SWIPENOTREGISTERED,
	WORKEDFROMANOTHEROFFICE,
	WORKEDONCOMPANYDECLAREDHOLIDAY,
	WORKEDONWEEKLYOFF,
	WORKFROMHOME
	
	
}
